# Generated by Django 5.1.5 on 2025-02-11 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_review'),
    ]

    operations = [
    ]
